```sql
/* ================================================================
   THE GREEN WARDEN
   COMPLETE SUPABASE BACKEND
   MATCHED TO dashboard.html

   Dashboard contracts covered:

   AUTH
   ────────────────────────────────────────────────────────────────
   get_my_status()

   CHECK-IN
   ────────────────────────────────────────────────────────────────
   claim_checkin()
   record_portal_activity()

   TASKS
   ────────────────────────────────────────────────────────────────
   get_task_board()
   submit_task_for_review(text,text)
   get_admin_task_reviews()
   approve_task_claim(uuid,text)
   reject_task_claim(uuid,text)

   LEADERBOARD
   ────────────────────────────────────────────────────────────────
   get_leaderboard(integer)
   get_admin_leaderboard()

   PROFILE
   ────────────────────────────────────────────────────────────────
   update_profile(text,text,text)
   get_admin_profile(uuid)

   REFERRALS
   ────────────────────────────────────────────────────────────────
   generate_referral_code()
   get_my_referral_code()
   get_my_referral_data()
   attach_referral(text)
   qualify_referral(uuid)
   qualify_my_referral()

   REWARD LADDER
   ────────────────────────────────────────────────────────────────
   Day 1 = 5 WP
   Day 2 = 10 WP
   Day 3 = 15 WP
   Day 4 = 20 WP
   Day 5 = 25 WP
   Day 6 = 30 WP
   Day 7 = 50 WP

   REFERRAL REWARD
   ────────────────────────────────────────────────────────────────
   Successful / qualified referral = EXACTLY +200 WP
   Attachment alone = 0 WP
   Same referral cannot pay twice.

   IMPORTANT
   ────────────────────────────────────────────────────────────────
   No tables are dropped.
   Existing data is preserved.
   ================================================================= */


/* ================================================================
   SECTION 1
   EXTENSIONS
   ================================================================ */

create extension if not exists pgcrypto;


/* ================================================================
   SECTION 2
   TABLE SAFETY / REQUIRED COLUMNS
   ================================================================ */


/* ------------------------------------------------
   PROFILES
   ------------------------------------------------ */

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    google_name text,
    avatar_url text,
    username text,
    x_username text,
    wp integer not null default 0,
    streak integer not null default 0,
    best_streak integer not null default 0,
    last_checkin date,
    created_at timestamptz not null default now(),
    wallet_address text,
    x_bonus_claimed boolean not null default false,
    wallet_bonus_claimed boolean not null default false,
    is_admin boolean not null default false
);


/* ------------------------------------------------
   CHECKINS
   ------------------------------------------------ */

create table if not exists public.checkins (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    day date not null,
    day_in_cycle integer not null,
    wp_awarded integer not null,
    created_at timestamptz not null default now()
);


/* Existing installations may already have the table
   without the identity id. */
alter table public.checkins
    add column if not exists id bigint;


/* ------------------------------------------------
   TASKS
   ------------------------------------------------ */

create table if not exists public.tasks (
    id text primary key,
    label text not null,
    url text not null,
    wp_reward integer not null,
    needs_proof boolean not null default false,
    active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);


/* ------------------------------------------------
   TASK CLAIMS
   ------------------------------------------------ */

create table if not exists public.task_claims (
    user_id uuid not null references auth.users(id) on delete cascade,
    task_id text not null references public.tasks(id) on delete cascade,
    wp_awarded integer not null default 0,
    proof_url text,
    claimed_at timestamptz not null default now(),
    status text default 'pending',
    reviewed_at timestamptz,
    reviewed_by uuid references auth.users(id),
    primary key (user_id, task_id)
);


/* ------------------------------------------------
   REFERRAL CODES
   ------------------------------------------------ */

create table if not exists public.referral_codes (
    user_id uuid primary key references auth.users(id) on delete cascade,
    referral_code text not null,
    created_at timestamptz not null default now()
);


/* ------------------------------------------------
   REFERRALS
   ------------------------------------------------ */

create table if not exists public.referrals (
    id bigint generated by default as identity primary key,
    referrer_id uuid not null references auth.users(id) on delete cascade,
    referred_id uuid not null references auth.users(id) on delete cascade,
    referral_code text not null,
    created_at timestamptz not null default now(),

    initial_reward integer not null default 300,
    initial_rewarded_at timestamptz,

    active_reward integer not null default 200,
    active_rewarded_at timestamptz,

    qualified_at timestamptz
);


/* ------------------------------------------------
   REFERRAL REWARDS
   ------------------------------------------------ */

create table if not exists public.referral_rewards (
    id bigint generated by default as identity primary key,
    referral_id bigint not null references public.referrals(id) on delete cascade,
    referrer_id uuid not null references auth.users(id) on delete cascade,
    reward_type text not null,
    wp_awarded integer not null,
    created_at timestamptz not null default now()
);


/* ================================================================
   SECTION 3
   INDEXES
   ================================================================ */

create unique index if not exists referral_codes_code_uidx
on public.referral_codes(referral_code);


create unique index if not exists referrals_referred_uidx
on public.referrals(referred_id);


create unique index if not exists referral_rewards_success_once_uidx
on public.referral_rewards(referral_id, reward_type);


create unique index if not exists checkins_user_day_uidx
on public.checkins(user_id, day);


create index if not exists checkins_user_day_idx
on public.checkins(user_id, day desc);


create index if not exists task_claims_user_idx
on public.task_claims(user_id);


create index if not exists task_claims_status_idx
on public.task_claims(status);


create index if not exists tasks_active_sort_idx
on public.tasks(active, sort_order);


/* ================================================================
   SECTION 4
   PROFILE AUTO-CREATION
   ================================================================ */

create or replace function public.ensure_profile()
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid := auth.uid();
    v_profile public.profiles;
begin

    if v_user is null then
        raise exception 'NOT_AUTHENTICATED';
    end if;


    insert into public.profiles (
        id,
        google_name,
        avatar_url
    )
    select
        u.id,
        coalesce(
            u.raw_user_meta_data->>'full_name',
            u.raw_user_meta_data->>'name'
        ),
        u.raw_user_meta_data->>'avatar_url'
    from auth.users u
    where u.id = v_user
    on conflict (id) do nothing;


    select *
    into v_profile
    from public.profiles
    where id = v_user;


    return v_profile;

end;
$$;


/* ================================================================
   SECTION 5
   MANILA DATE / RESET HELPERS
   ================================================================ */

create or replace function public.manila_today()
returns date
language sql
stable
as $$
    select (now() at time zone 'Asia/Manila')::date;
$$;


create or replace function public.manila_seconds_to_reset()
returns integer
language plpgsql
stable
as $$
declare
    v_now timestamp;
    v_next timestamp;
begin

    v_now :=
        now() at time zone 'Asia/Manila';

    v_next :=
        date_trunc('day', v_now) + interval '1 day';

    return greatest(
        0,
        extract(
            epoch from (v_next - v_now)
        )::integer
    );
end;
$$;


/* ================================================================
   SECTION 6
   REWARD LADDER
   ================================================================ */

create or replace function public.wp_for_day(
    p_day integer
)
returns integer
language sql
immutable
as $$
    select case
        when p_day = 1 then 5
        when p_day = 2 then 10
        when p_day = 3 then 15
        when p_day = 4 then 20
        when p_day = 5 then 25
        when p_day = 6 then 30
        when p_day = 7 then 50
        else 5
    end;
$$;


/* ================================================================
   SECTION 7
   EFFECTIVE STREAK
   ================================================================ */

create or replace function public.effective_streak(
    p_last date,
    p_streak integer
)
returns integer
language plpgsql
immutable
as $$
begin

    if p_last is null then
        return 0;
    end if;

    if p_last = current_date then
        return greatest(0, p_streak);
    end if;

    if p_last = current_date - 1 then
        return greatest(0, p_streak);
    end if;

    return 0;

end;
$$;


/* ================================================================
   SECTION 8
   GET MY STATUS
   ================================================================

   Returns the exact fields consumed by dashboard.html:

       id
       username
       google_name
       avatar_url
       x_username
       wallet_address
       wp
       streak
       best_streak
       last_checkin
       claimed_today
       day
       day_in_cycle
       wp_awarded
       seconds_to_reset
       rank
   ================================================================ */

create or replace function public.get_my_status()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    p public.profiles;

    v_today date;

    v_claimed boolean := false;

    v_day integer := 1;

    v_wp integer := 5;

    v_rank bigint := 0;

    v_streak integer := 0;

begin

    if v_user is null then
        raise exception 'NOT_AUTHENTICATED';
    end if;


    p := public.ensure_profile();

    v_today := public.manila_today();


    select exists (
        select 1
        from public.checkins c
        where c.user_id = v_user
          and c.day = v_today
    )
    into v_claimed;


    v_streak := public.effective_streak(
        p.last_checkin,
        p.streak
    );


    if v_claimed then

        select
            c.day_in_cycle,
            c.wp_awarded
        into
            v_day,
            v_wp
        from public.checkins c
        where c.user_id = v_user
          and c.day = v_today
        order by c.created_at desc
        limit 1;

    else

        v_day :=
            case
                when v_streak > 0
                    then ((v_streak % 7) + 1)
                else 1
            end;

        v_wp :=
            public.wp_for_day(v_day);

    end if;


    select count(*) + 1
    into v_rank
    from public.profiles p2
    where p2.wp > p.wp;


    return json_build_object(

        'id',
            p.id,

        'username',
            p.username,

        'google_name',
            p.google_name,

        'avatar_url',
            p.avatar_url,

        'x_username',
            p.x_username,

        'wallet_address',
            p.wallet_address,

        'wp',
            coalesce(p.wp, 0),

        'streak',
            v_streak,

        'best_streak',
            coalesce(p.best_streak, 0),

        'last_checkin',
            p.last_checkin,

        'claimed_today',
            v_claimed,

        'day',
            v_day,

        'day_in_cycle',
            v_day,

        'wp_awarded',
            v_wp,

        'seconds_to_reset',
            public.manila_seconds_to_reset(),

        'rank',
            v_rank,

        'is_admin',
            coalesce(p.is_admin, false)

    );

end;
$$;


/* ================================================================
   SECTION 9
   CLAIM CHECK-IN
   ================================================================ */

create or replace function public.claim_checkin()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_today date;

    v_profile public.profiles;

    v_day integer;

    v_reward integer;

    v_new_streak integer;

    v_best integer;

begin

    if v_user is null then
        raise exception 'NOT_AUTHENTICATED';
    end if;


    v_profile := public.ensure_profile();

    v_today := public.manila_today();


    /* ------------------------------------------------------------
       Prevent duplicate daily claim
       ------------------------------------------------------------ */

    if exists (
        select 1
        from public.checkins
        where user_id = v_user
          and day = v_today
    ) then

        return json_build_object(
            'ok', false,
            'wp_awarded', 0,
            'day', (
                select day_in_cycle
                from public.checkins
                where user_id = v_user
                  and day = v_today
                limit 1
            ),
            'streak', v_profile.streak
        );

    end if;


    /* ------------------------------------------------------------
       Determine streak
       ------------------------------------------------------------ */

    if v_profile.last_checkin = v_today - 1 then

        v_new_streak :=
            greatest(0, v_profile.streak) + 1;

    else

        v_new_streak := 1;

    end if;


    v_day :=
        ((v_new_streak - 1) % 7) + 1;


    v_reward :=
        public.wp_for_day(v_day);


    v_best :=
        greatest(
            coalesce(v_profile.best_streak, 0),
            v_new_streak
        );


    /* ------------------------------------------------------------
       Record check-in
       ------------------------------------------------------------ */

    insert into public.checkins (
        user_id,
        day,
        day_in_cycle,
        wp_awarded
    )
    values (
        v_user,
        v_today,
        v_day,
        v_reward
    );


    /* ------------------------------------------------------------
       Award WP
       ------------------------------------------------------------ */

    update public.profiles
    set
        wp = coalesce(wp, 0) + v_reward,
        streak = v_new_streak,
        best_streak = v_best,
        last_checkin = v_today
    where id = v_user;


    /* ------------------------------------------------------------
       Referral qualification is checked separately by
       qualify_referral() as dashboard.html expects.
       ------------------------------------------------------------ */


    return json_build_object(

        'ok',
            true,

        'wp_awarded',
            v_reward,

        'day',
            v_day,

        'streak',
            v_new_streak

    );

end;
$$;


/* ================================================================
   SECTION 10
   PORTAL ACTIVITY
   ================================================================ */

create or replace function public.record_portal_activity()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid := auth.uid();
    v_profile public.profiles;
begin

    if v_user is null then
        return jsonb_build_object(
            'ok', false,
            'error', 'NOT_AUTHENTICATED'
        );
    end if;


    v_profile := public.ensure_profile();


    return jsonb_build_object(
        'ok', true,
        'user_id', v_user,
        'streak', coalesce(v_profile.streak, 0),
        'last_checkin', v_profile.last_checkin
    );

end;
$$;


/* ================================================================
   SECTION 11
   TASK BOARD
   ================================================================

   IMPORTANT:
   Dashboard.html supports:

       {
         ok: true,
         tasks: [...],
         task_claims: [...]
       }

   We intentionally return this object form so dashboard.html does
   not enter its legacy array branch that queries nonexistent
   task_claims.id / task_claims.created_at columns.
   ================================================================ */

create or replace function public.get_task_board()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_tasks jsonb;

    v_claims jsonb;

begin

    if v_user is null then
        return jsonb_build_object(
            'ok', false,
            'error', 'NOT_AUTHENTICATED',
            'tasks', '[]'::jsonb,
            'task_claims', '[]'::jsonb
        );
    end if;


    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', t.id,
                'label', t.label,
                'title', t.label,
                'description', '',
                'platform', 'X',
                'task_type', 'social',
                'url', t.url,
                'task_url', t.url,
                'wp_reward', t.wp_reward,
                'reward_wp', t.wp_reward,
                'needs_proof', t.needs_proof,
                'active', t.active,
                'sort_order', t.sort_order,
                'completed',
                    exists (
                        select 1
                        from public.task_claims tc
                        where tc.user_id = v_user
                          and tc.task_id = t.id
                          and tc.status = 'approved'
                    )
            )
            order by t.sort_order, t.created_at
        ),
        '[]'::jsonb
    )
    into v_tasks
    from public.tasks t
    where t.active = true;


    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'user_id', tc.user_id,
                'task_id', tc.task_id,
                'proof_url', tc.proof_url,
                'wp_awarded', tc.wp_awarded,
                'status', coalesce(tc.status, 'pending'),
                'claimed_at', tc.claimed_at,
                'reviewed_at', tc.reviewed_at,
                'reviewed_by', tc.reviewed_by
            )
            order by tc.claimed_at desc
        ),
        '[]'::jsonb
    )
    into v_claims
    from public.task_claims tc
    where tc.user_id = v_user;


    return jsonb_build_object(
        'ok', true,
        'tasks', v_tasks,
        'task_claims', v_claims
    );

end;
$$;


/* ================================================================
   SECTION 12
   SUBMIT TASK FOR REVIEW
   ================================================================ */

create or replace function public.submit_task_for_review(
    p_task_id text,
    p_proof_url text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_task public.tasks;

    v_existing public.task_claims;

    v_url text;

begin

    if v_user is null then
        return jsonb_build_object(
            'ok', false,
            'error', 'NOT_AUTHENTICATED'
        );
    end if;


    if p_task_id is null
       or trim(p_task_id) = '' then

        return jsonb_build_object(
            'ok', false,
            'error', 'INVALID_TASK'
        );

    end if;


    select *
    into v_task
    from public.tasks
    where id = p_task_id
      and active = true;


    if not found then

        return jsonb_build_object(
            'ok', false,
            'error', 'TASK_NOT_FOUND'
        );

    end if;


    if v_task.needs_proof then

        v_url := trim(coalesce(p_proof_url, ''));


        if v_url = '' then

            return jsonb_build_object(
                'ok', false,
                'error', 'PROOF_REQUIRED'
            );

        end if;


        if v_url !~* '^https?://(www\.)?(x\.com|twitter\.com)/.+$' then

            return jsonb_build_object(
                'ok', false,
                'error', 'INVALID_PROOF_URL'
            );

        end if;

    else

        v_url := null;

    end if;


    select *
    into v_existing
    from public.task_claims
    where user_id = v_user
      and task_id = p_task_id;


    if found and v_existing.status = 'approved' then

        return jsonb_build_object(
            'ok', false,
            'error', 'ALREADY_APPROVED'
        );

    end if;


    /* ------------------------------------------------------------
       Existing rejected/pending claim is reused.
       This lets a rejected submission be resubmitted.
       ------------------------------------------------------------ */

    insert into public.task_claims (
        user_id,
        task_id,
        proof_url,
        wp_awarded,
        status,
        claimed_at,
        reviewed_at,
        reviewed_by
    )
    values (
        v_user,
        p_task_id,
        v_url,
        0,
        'pending',
        now(),
        null,
        null
    )
    on conflict (user_id, task_id)
    do update set
        proof_url = excluded.proof_url,
        status = 'pending',
        claimed_at = now(),
        reviewed_at = null,
        reviewed_by = null;


    return jsonb_build_object(
        'ok', true,
        'status', 'pending',
        'task_id', p_task_id,
        'wp_awarded', 0
    );

end;
$$;


/* ================================================================
   SECTION 13
   ADMIN CHECK
   ================================================================ */

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and is_admin = true
    );
$$;


/* ================================================================
   SECTION 14
   ADMIN TASK REVIEWS
   ================================================================ */

create or replace function public.get_admin_task_reviews()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_claims jsonb;
begin

    if not public.is_current_user_admin() then

        return jsonb_build_object(
            'ok', false,
            'error', 'ADMIN_REQUIRED',
            'claims', '[]'::jsonb
        );

    end if;


    select coalesce(
        jsonb_agg(
            jsonb_build_object(

                'user_id',
                    tc.user_id,

                'task_id',
                    tc.task_id,

                'task_label',
                    t.label,

                'wp_reward',
                    t.wp_reward,

                'wp_awarded',
                    tc.wp_awarded,

                'proof_url',
                    tc.proof_url,

                'status',
                    tc.status,

                'claimed_at',
                    tc.claimed_at,

                'reviewed_at',
                    tc.reviewed_at,

                'reviewed_by',
                    tc.reviewed_by,

                'username',
                    p.username,

                'google_name',
                    p.google_name,

                'x_username',
                    p.x_username,

                'avatar_url',
                    p.avatar_url

            )
            order by tc.claimed_at asc
        ),
        '[]'::jsonb
    )
    into v_claims

    from public.task_claims tc

    join public.tasks t
      on t.id = tc.task_id

    left join public.profiles p
      on p.id = tc.user_id

    where tc.status = 'pending';


    return jsonb_build_object(
        'ok', true,
        'claims', v_claims
    );

end;
$$;


/* ================================================================
   SECTION 15
   APPROVE TASK CLAIM
   ================================================================ */

create or replace function public.approve_task_claim(
    p_user_id uuid,
    p_task_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare

    v_claim public.task_claims;

    v_task public.tasks;

    v_admin uuid := auth.uid();

begin

    if not public.is_current_user_admin() then

        return jsonb_build_object(
            'ok', false,
            'error', 'ADMIN_REQUIRED'
        );

    end if;


    select *
    into v_claim
    from public.task_claims
    where user_id = p_user_id
      and task_id = p_task_id
    for update;


    if not found then

        return jsonb_build_object(
            'ok', false,
            'error', 'CLAIM_NOT_FOUND'
        );

    end if;


    if v_claim.status = 'approved' then

        return jsonb_build_object(
            'ok', false,
            'error', 'ALREADY_APPROVED'
        );

    end if;


    select *
    into v_task
    from public.tasks
    where id = p_task_id;


    if not found then

        return jsonb_build_object(
            'ok', false,
            'error', 'TASK_NOT_FOUND'
        );

    end if;


    update public.task_claims
    set
        status = 'approved',
        wp_awarded = v_task.wp_reward,
        reviewed_at = now(),
        reviewed_by = v_admin
    where user_id = p_user_id
      and task_id = p_task_id;


    update public.profiles
    set
        wp = coalesce(wp, 0) + v_task.wp_reward
    where id = p_user_id;


    return jsonb_build_object(
        'ok', true,
        'status', 'approved',
        'wp_awarded', v_task.wp_reward
    );

end;
$$;


/* ================================================================
   SECTION 16
   REJECT TASK CLAIM
   ================================================================ */

create or replace function public.reject_task_claim(
    p_user_id uuid,
    p_task_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_admin uuid := auth.uid();
begin

    if not public.is_current_user_admin() then

        return jsonb_build_object(
            'ok', false,
            'error', 'ADMIN_REQUIRED'
        );

    end if;


    update public.task_claims
    set
        status = 'rejected',
        wp_awarded = 0,
        reviewed_at = now(),
        reviewed_by = v_admin
    where user_id = p_user_id
      and task_id = p_task_id;


    if not found then

        return jsonb_build_object(
            'ok', false,
            'error', 'CLAIM_NOT_FOUND'
        );

    end if;


    return jsonb_build_object(
        'ok', true,
        'status', 'rejected',
        'wp_awarded', 0
    );

end;
$$;


/* ================================================================
   SECTION 17
   LEADERBOARD
   ================================================================ */

create or replace function public.get_leaderboard(
    p_limit integer
)
returns table (
    pos bigint,
    display text,
    avatar text,
    x_handle text,
    points integer,
    day_streak integer,
    me boolean
)
language sql
security definer
set search_path = public
as $$
    with ranked as (

        select
            p.id,
            row_number() over (
                order by
                    p.wp desc,
                    p.streak desc,
                    p.created_at asc
            ) as position,
            coalesce(
                nullif(p.username, ''),
                nullif(p.google_name, ''),
                'Warden'
            ) as display_name,
            p.avatar_url,
            p.x_username,
            coalesce(p.wp, 0) as wp_points,
            public.effective_streak(
                p.last_checkin,
                p.streak
            ) as current_streak

        from public.profiles p

        where p.wp > 0

        order by
            p.wp desc,
            p.streak desc,
            p.created_at asc

        limit greatest(
            1,
            least(
                coalesce(p_limit, 50),
                100
            )
        )
    )

    select
        position::bigint,
        display_name,
        avatar_url,
        x_username,
        wp_points,
        current_streak,
        id = auth.uid()

    from ranked;
$$;


/* ================================================================
   SECTION 18
   ADMIN LEADERBOARD
   ================================================================ */

create or replace function public.get_admin_leaderboard()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_profiles jsonb;
begin

    if not public.is_current_user_admin() then

        return jsonb_build_object(
            'ok', false,
            'error', 'ADMIN_REQUIRED',
            'profiles', '[]'::jsonb
        );

    end if;


    select coalesce(
        jsonb_agg(
            jsonb_build_object(

                'user_id',
                    p.id,

                'username',
                    p.username,

                'google_name',
                    p.google_name,

                'x_username',
                    p.x_username,

                'avatar_url',
                    p.avatar_url,

                'wp',
                    coalesce(p.wp, 0),

                'streak',
                    public.effective_streak(
                        p.last_checkin,
                        p.streak
                    ),

                'best_streak',
                    coalesce(p.best_streak, 0),

                'last_checkin',
                    p.last_checkin

            )
            order by
                p.wp desc,
                p.streak desc,
                p.created_at asc
        ),
        '[]'::jsonb
    )
    into v_profiles
    from public.profiles p;


    return jsonb_build_object(
        'ok', true,
        'profiles', v_profiles
    );

end;
$$;


/* ================================================================
   SECTION 19
   ADMIN PROFILE
   ================================================================ */

create or replace function public.get_admin_profile(
    p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_profile public.profiles;
begin

    if not public.is_current_user_admin() then

        return jsonb_build_object(
            'ok', false,
            'error', 'ADMIN_REQUIRED'
        );

    end if;


    select *
    into v_profile
    from public.profiles
    where id = p_user_id;


    if not found then

        return jsonb_build_object(
            'ok', false,
            'error', 'PROFILE_NOT_FOUND'
        );

    end if;


    return jsonb_build_object(

        'ok', true,

        'profile',
            jsonb_build_object(

                'user_id',
                    v_profile.id,

                'username',
                    v_profile.username,

                'google_name',
                    v_profile.google_name,

                'x_username',
                    v_profile.x_username,

                'avatar_url',
                    v_profile.avatar_url,

                'wp',
                    coalesce(v_profile.wp, 0),

                'streak',
                    public.effective_streak(
                        v_profile.last_checkin,
                        v_profile.streak
                    ),

                'best_streak',
                    coalesce(v_profile.best_streak, 0),

                'last_checkin',
                    v_profile.last_checkin

            )

    );

end;
$$;


/* ================================================================
   SECTION 20
   SOLANA ADDRESS VALIDATION
   ================================================================ */

create or replace function public.is_valid_solana_address(
    p_wallet text
)
returns boolean
language plpgsql
immutable
as $$
begin

    if p_wallet is null
       or length(trim(p_wallet)) < 32
       or length(trim(p_wallet)) > 44 then

        return false;

    end if;


    return trim(p_wallet) ~
        '^[1-9A-HJ-NP-Za-km-z]{32,44}$';

end;
$$;


/* ================================================================
   SECTION 21
   UPDATE PROFILE
   ================================================================ */

create or replace function public.update_profile(
    p_username text,
    p_x_username text,
    p_wallet_address text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_profile public.profiles;

    v_username text :=
        nullif(trim(coalesce(p_username, '')), '');

    v_x text :=
        nullif(
            trim(
                regexp_replace(
                    coalesce(p_x_username, ''),
                    '^@+',
                    ''
                )
            ),
            ''
        );

    v_wallet text :=
        nullif(trim(coalesce(p_wallet_address, '')), '');

    v_x_bonus integer := 0;

    v_wallet_bonus integer := 0;

begin

    if v_user is null then

        return json_build_object(
            'ok', false,
            'error', 'NOT_AUTHENTICATED'
        );

    end if;


    perform public.ensure_profile();


    /* ------------------------------------------------------------
       Username validation
       ------------------------------------------------------------ */

    if v_username is not null
       and v_username !~ '^[A-Za-z0-9_]{3,20}$' then

        return json_build_object(
            'ok', false,
            'error', 'INVALID_USERNAME'
        );

    end if;


    /* ------------------------------------------------------------
       X validation
       ------------------------------------------------------------ */

    if v_x is not null
       and v_x !~ '^[A-Za-z0-9_]{1,15}$' then

        return json_build_object(
            'ok', false,
            'error', 'INVALID_X'
        );

    end if;


    /* ------------------------------------------------------------
       Wallet validation
       ------------------------------------------------------------ */

    if v_wallet is not null
       and not public.is_valid_solana_address(v_wallet) then

        return json_build_object(
            'ok', false,
            'error', 'INVALID_WALLET'
        );

    end if;


    /* ------------------------------------------------------------
       Username uniqueness
       ------------------------------------------------------------ */

    if v_username is not null
       and exists (
            select 1
            from public.profiles p
            where lower(p.username) = lower(v_username)
              and p.id <> v_user
       ) then

        return json_build_object(
            'ok', false,
            'error', 'USERNAME_TAKEN'
        );

    end if;


    select *
    into v_profile
    from public.profiles
    where id = v_user
    for update;


    /* ------------------------------------------------------------
       First-time X bonus = +5 WP
       ------------------------------------------------------------ */

    if v_x is not null
       and coalesce(v_profile.x_username, '') = ''
       and not v_profile.x_bonus_claimed then

        v_x_bonus := 5;

    end if;


    /* ------------------------------------------------------------
       First-time wallet bonus = +5 WP
       ------------------------------------------------------------ */

    if v_wallet is not null
       and coalesce(v_profile.wallet_address, '') = ''
       and not v_profile.wallet_bonus_claimed then

        v_wallet_bonus := 5;

    end if;


    update public.profiles
    set

        username = v_username,

        x_username = v_x,

        wallet_address = v_wallet,

        x_bonus_claimed =
            case
                when v_x_bonus > 0 then true
                else x_bonus_claimed
            end,

        wallet_bonus_claimed =
            case
                when v_wallet_bonus > 0 then true
                else wallet_bonus_claimed
            end,

        wp =
            coalesce(wp, 0)
            + v_x_bonus
            + v_wallet_bonus

    where id = v_user

    returning *
    into v_profile;


    return json_build_object(

        'ok', true,

        'username',
            v_profile.username,

        'x_username',
            v_profile.x_username,

        'wallet_address',
            v_profile.wallet_address,

        'x_bonus',
            v_x_bonus,

        'wallet_bonus',
            v_wallet_bonus,

        'total_bonus',
            v_x_bonus + v_wallet_bonus

    );

end;
$$;


/* ================================================================
   SECTION 22
   REFERRAL CODE GENERATOR
   ================================================================ */

create or replace function public.generate_referral_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_existing text;

    v_code text;

begin

    if v_user is null then
        raise exception 'AUTH_REQUIRED';
    end if;


    select referral_code
    into v_existing
    from public.referral_codes
    where user_id = v_user
    limit 1;


    if v_existing is not null then
        return v_existing;
    end if;


    v_code :=
        'GW' ||
        upper(
            substr(
                replace(v_user::text, '-', ''),
                1,
                8
            )
        );


    begin

        insert into public.referral_codes (
            user_id,
            referral_code
        )
        values (
            v_user,
            v_code
        );

    exception
        when unique_violation then

            v_code :=
                'GW' ||
                upper(
                    substr(
                        replace(v_user::text, '-', ''),
                        1,
                        12
                    )
                );

            insert into public.referral_codes (
                user_id,
                referral_code
            )
            values (
                v_user,
                v_code
            );

    end;


    return v_code;

end;
$$;


/* ================================================================
   SECTION 23
   GET MY REFERRAL CODE
   ================================================================ */

create or replace function public.get_my_referral_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_code text;

begin

    if v_user is null then
        raise exception 'AUTH_REQUIRED';
    end if;


    select referral_code
    into v_code
    from public.referral_codes
    where user_id = v_user
    limit 1;


    if v_code is null then
        v_code := public.generate_referral_code();
    end if;


    return v_code;

end;
$$;


/* ================================================================
   SECTION 24
   REFERRAL DATA
   ================================================================ */

create or replace function public.get_my_referral_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_code text;

    v_total integer := 0;

    v_successful integer := 0;

    v_reward_count integer := 0;

    v_total_wp integer := 0;

    v_referred boolean := false;

    v_qualified boolean := false;

    v_streak integer := 0;

    v_today date;

begin

    if v_user is null then
        raise exception 'AUTH_REQUIRED';
    end if;


    v_code := public.get_my_referral_code();

    v_today := public.manila_today();


    select count(*)
    into v_total
    from public.referrals
    where referrer_id = v_user;


    select count(*)
    into v_successful
    from public.referrals
    where referrer_id = v_user
      and qualified_at is not null;


    select
        count(*),
        coalesce(sum(wp_awarded), 0)
    into
        v_reward_count,
        v_total_wp
    from public.referral_rewards
    where referrer_id = v_user;


    select exists (
        select 1
        from public.referrals
        where referred_id = v_user
    )
    into v_referred;


    /* ------------------------------------------------------------
       Current streak for the referred user
       ------------------------------------------------------------ */

    select coalesce(
        (
            select p.streak
            from public.profiles p
            where p.id = v_user
        ),
        0
    )
    into v_streak;


    select exists (
        select 1
        from public.referrals r
        where r.referred_id = v_user
          and r.qualified_at is not null
    )
    into v_qualified;


    return jsonb_build_object(

        'referral_code',
            v_code,

        'referral_link',
            '?ref=' || v_code,

        /* dashboard fields */
        'total_referrals',
            v_total,

        'total_wp_earned',
            v_total_wp,

        'my_activity_streak',
            least(7, greatest(0, v_streak)),

        'my_7_day_qualified',
            v_qualified,

        /* compatibility fields */
        'referral_count',
            v_total,

        'successful_referrals',
            v_successful,

        'reward_count',
            v_reward_count,

        'activity_streak',
            v_streak,

        'days_remaining',
            greatest(
                0,
                7 - least(7, greatest(0, v_streak))
            ),

        'qualified',
            v_qualified,

        'has_been_referred',
            v_referred

    );

end;
$$;


/* ================================================================
   SECTION 25
   ATTACH REFERRAL
   ================================================================

   IMPORTANT:

   Attaching a referral does NOT award WP.

   The dashboard text currently says "+200" when attachment
   succeeds, but the actual reward rule is:

       successful referral = +200 WP

   Therefore payment is performed by qualify_referral().
   ================================================================ */

create or replace function public.attach_referral(
    p_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare

    v_user uuid := auth.uid();

    v_code text :=
        upper(trim(coalesce(p_code, '')));

    v_referrer uuid;

    v_id bigint;

begin

    if v_user is null then

        return jsonb_build_object(
            'ok', false,
            'success', false,
            'message', 'AUTH_REQUIRED'
        );

    end if;


    if v_code = '' then

        return jsonb_build_object(
            'ok', false,
            'success', false,
            'message', 'INVALID_CODE'
        );

    end if;


    select user_id
    into v_referrer
    from public.referral_codes
    where upper(referral_code) = v_code
    limit 1;


    if v_referrer is null then

        return jsonb_build_object(
            'ok', false,
            'success', false,
            'message', 'REFERRAL_CODE_NOT_FOUND'
        );

    end if;


    if v_referrer = v_user then

        return jsonb_build_object(
            'ok', false,
            'success', false,
            'message', 'SELF_REFERRAL'
        );

    end if;


    if exists (
        select 1
        from public.referrals
        where referred_id = v_user
    ) then

        return jsonb_build_object(
            'ok', false,
            'success', false,
            'message', 'ALREADY_REFERRED'
        );

    end if;


    insert into public.referrals (
        referrer_id,
        referred_id,
        referral_code
    )
    values (
        v_referrer,
        v_user,
        v_code
    )
    returning id
    into v_id;


    return jsonb_build_object(

        'ok',
            true,

        'success',
            true,

        'message',
            'REFERRAL_ATTACHED',

        'referral_id',
            v_id,

        'wp_awarded',
            0

    );

end;
$$;


/* ================================================================
   SECTION 26
   QUALIFY REFERRAL
   ================================================================

   Qualification:

   - Referral must exist.
   - Referred Warden must maintain a 7-day consecutive
     activity/check-in streak.
   - Qualification happens only once.
   - Referrer receives EXACTLY +200 WP.
   - referral_rewards receives one successful_referral row.
   - No duplicate reward.
   ================================================================ */

create or replace function public.qualify_referral(
    p_referred_user uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare

    v_referral public.referrals%rowtype;

    v_streak integer := 0;

    v_reward integer := 200;

begin

    if p_referred_user is null then

        return jsonb_build_object(
            'ok', false,
            'rewarded', false,
            'error', 'INVALID_USER'
        );

    end if;


    select *
    into v_referral
    from public.referrals
    where referred_id = p_referred_user
    order by created_at asc
    limit 1
    for update;


    if not found then

        return jsonb_build_object(
            'ok', true,
            'rewarded', false,
            'error', 'NO_REFERRAL'
        );

    end if;


    if v_referral.qualified_at is not null then

        return jsonb_build_object(
            'ok', true,
            'rewarded', false,
            'already_qualified', true,
            'wp_awarded', 0
        );

    end if;


    /* ------------------------------------------------------------
       Read the server-maintained streak.
       claim_checkin() increments this only when the user checks
       in on consecutive Manila dates.
       ------------------------------------------------------------ */

    select coalesce(streak, 0)
    into v_streak
    from public.profiles
    where id = p_referred_user;


    if v_streak < 7 then

        return jsonb_build_object(

            'ok', true,

            'rewarded', false,

            'streak',
                v_streak,

            'required',
                7,

            'wp_awarded',
                0

        );

    end if;


    /* ------------------------------------------------------------
       Mark qualified.
       ------------------------------------------------------------ */

    update public.referrals
    set
        qualified_at = now(),
        active_rewarded_at = now()
    where id = v_referral.id;


    /* ------------------------------------------------------------
       Insert reward only once.
       The unique index prevents duplicate successful rewards.
       ------------------------------------------------------------ */

    insert into public.referral_rewards (
        referral_id,
        referrer_id,
        reward_type,
        wp_awarded
    )
    values (
        v_referral.id,
        v_referral.referrer_id,
        'successful_referral',
        v_reward
    )
    on conflict (
        referral_id,
        reward_type
    )
    do nothing;


    /* ------------------------------------------------------------
       Only increase referrer's WP if the reward row was newly
       inserted.

       This prevents a repeated RPC call from paying +200 again.
       ------------------------------------------------------------ */

    if found then

        update public.profiles
        set wp = coalesce(wp, 0) + v_reward
        where id = v_referral.referrer_id;

    else

        return jsonb_build_object(
            'ok', true,
            'rewarded', false,
            'already_qualified', true,
            'wp_awarded', 0
        );

    end if;


    return jsonb_build_object(

        'ok',
            true,

        'rewarded',
            true,

        'streak',
            v_streak,

        'required',
            7,

        'wp_awarded',
            v_reward,

        'referral_id',
            v_referral.id,

        'referrer_id',
            v_referral.referrer_id

    );

end;
$$;


/* ================================================================
   SECTION 27
   QUALIFY MY REFERRAL
   ================================================================ */

create or replace function public.qualify_my_referral()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin

    if auth.uid() is null then

        return jsonb_build_object(
            'ok', false,
            'rewarded', false,
            'error', 'AUTH_REQUIRED'
        );

    end if;


    return public.qualify_referral(auth.uid());

end;
$$;


/* ================================================================
   SECTION 28
   RLS
   ================================================================ */

alter table public.profiles enable row level security;
alter table public.checkins enable row level security;
alter table public.tasks enable row level security;
alter table public.task_claims enable row level security;
alter table public.referral_codes enable row level security;
alter table public.referrals enable row level security;
alter table public.referral_rewards enable row level security;


/* ------------------------------------------------
   Helper to safely create policies.
   ------------------------------------------------ */

do $$
begin

    /* profiles: users can read their own profile */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'profiles'
          and policyname = 'profiles_select_own'
    ) then

        create policy profiles_select_own
        on public.profiles
        for select
        to authenticated
        using (id = auth.uid());

    end if;


    /* tasks: authenticated users can see active tasks */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'tasks'
          and policyname = 'tasks_select_active'
    ) then

        create policy tasks_select_active
        on public.tasks
        for select
        to authenticated
        using (active = true);

    end if;


    /* task claims: users can see their own claims */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'task_claims'
          and policyname = 'task_claims_select_own'
    ) then

        create policy task_claims_select_own
        on public.task_claims
        for select
        to authenticated
        using (user_id = auth.uid());

    end if;


    /* referral code: own code */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'referral_codes'
          and policyname = 'referral_codes_select_own'
    ) then

        create policy referral_codes_select_own
        on public.referral_codes
        for select
        to authenticated
        using (user_id = auth.uid());

    end if;


    /* referrals: users can see referrals where they are involved */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'referrals'
          and policyname = 'referrals_select_involved'
    ) then

        create policy referrals_select_involved
        on public.referrals
        for select
        to authenticated
        using (
            referrer_id = auth.uid()
            or referred_id = auth.uid()
        );

    end if;


    /* referral rewards: referrer can see own rewards */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'referral_rewards'
          and policyname = 'referral_rewards_select_own'
    ) then

        create policy referral_rewards_select_own
        on public.referral_rewards
        for select
        to authenticated
        using (referrer_id = auth.uid());

    end if;


    /* check-ins: user can see own check-ins */
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'checkins'
          and policyname = 'checkins_select_own'
    ) then

        create policy checkins_select_own
        on public.checkins
        for select
        to authenticated
        using (user_id = auth.uid());

    end if;

end;
$$;


/* ================================================================
   SECTION 29
   FUNCTION PERMISSIONS
   ================================================================ */

revoke all on function public.ensure_profile() from public;
revoke all on function public.get_my_status() from public;
revoke all on function public.claim_checkin() from public;
revoke all on function public.record_portal_activity() from public;

revoke all on function public.get_task_board() from public;
revoke all on function public.submit_task_for_review(text,text) from public;
revoke all on function public.get_admin_task_reviews() from public;
revoke all on function public.approve_task_claim(uuid,text) from public;
revoke all on function public.reject_task_claim(uuid,text) from public;

revoke all on function public.get_leaderboard(integer) from public;
revoke all on function public.get_admin_leaderboard() from public;
revoke all on function public.get_admin_profile(uuid) from public;

revoke all on function public.update_profile(text,text,text) from public;

revoke all on function public.generate_referral_code() from public;
revoke all on function public.get_my_referral_code() from public;
revoke all on function public.get_my_referral_data() from public;
revoke all on function public.attach_referral(text) from public;
revoke all on function public.qualify_referral(uuid) from public;
revoke all on function public.qualify_my_referral() from public;


grant execute on function public.get_my_status()
to authenticated;

grant execute on function public.claim_checkin()
to authenticated;

grant execute on function public.record_portal_activity()
to authenticated;

grant execute on function public.get_task_board()
to authenticated;

grant execute on function public.submit_task_for_review(text,text)
to authenticated;

grant execute on function public.get_admin_task_reviews()
to authenticated;

grant execute on function public.approve_task_claim(uuid,text)
to authenticated;

grant execute on function public.reject_task_claim(uuid,text)
to authenticated;

grant execute on function public.get_leaderboard(integer)
to authenticated;

grant execute on function public.get_admin_leaderboard()
to authenticated;

grant execute on function public.get_admin_profile(uuid)
to authenticated;

grant execute on function public.update_profile(text,text,text)
to authenticated;

grant execute on function public.generate_referral_code()
to authenticated;

grant execute on function public.get_my_referral_code()
to authenticated;

grant execute on function public.get_my_referral_data()
to authenticated;

grant execute on function public.attach_referral(text)
to authenticated;

grant execute on function public.qualify_referral(uuid)
to authenticated;

grant execute on function public.qualify_my_referral()
to authenticated;


/* ================================================================
   SECTION 30
   DEFAULT TASKS
   ================================================================

   These match the fallback tasks already present in dashboard.html.
   If the task already exists, its current configuration is preserved.
   ================================================================ */

insert into public.tasks (
    id,
    label,
    url,
    wp_reward,
    needs_proof,
    active,
    sort_order
)
values
(
    'like-launch-post',
    'Like + Reply to the Green Warden post',
    'https://x.com/GreenWardenSol/status/2102614430681022855?s=20',
    50,
    true,
    true,
    1
),
(
    'share-launch-post',
    'Quote/Share the Green Warden post',
    'https://x.com/GreenWardenSol/status/2102614430681022855?s=20',
    50,
    true,
    true,
    2
)
on conflict (id)
do nothing;


/* ================================================================
   SECTION 31
   VERIFICATION
   ================================================================ */


/* Functions expected by dashboard.html */

select
    p.proname as function_name,
    pg_get_function_identity_arguments(p.oid) as arguments,
    pg_get_function_result(p.oid) as return_type
from pg_proc p
join pg_namespace n
    on n.oid = p.pronamespace
where n.nspname = 'public'
and p.proname in (

    'get_my_status',
    'claim_checkin',
    'record_portal_activity',

    'get_task_board',
    'submit_task_for_review',
    'get_admin_task_reviews',
    'approve_task_claim',
    'reject_task_claim',

    'get_leaderboard',
    'get_admin_leaderboard',
    'get_admin_profile',

    'update_profile',

    'generate_referral_code',
    'get_my_referral_code',
    'get_my_referral_data',
    'attach_referral',
    'qualify_referral',
    'qualify_my_referral'

)
order by
    p.proname,
    arguments;


/* Check task catalog */

select
    id,
    label,
    url,
    wp_reward,
    needs_proof,
    active,
    sort_order
from public.tasks
order by sort_order, created_at;


/* Check referral reward records */

select
    id,
    referral_id,
    referrer_id,
    reward_type,
    wp_awarded,
    created_at
from public.referral_rewards
order by created_at desc
limit 20;


/* Check referral relationships */

select
    id,
    referrer_id,
    referred_id,
    referral_code,
    active_reward,
    active_rewarded_at,
    qualified_at,
    created_at
from public.referrals
order by created_at desc
limit 20;


/* ================================================================
   END
   ================================================================ */
```
