/* ============================================================
   THE GREEN WARDEN — SUPABASE MASTER SETUP / REPAIR SCRIPT (v2)
   Safe to re-run. Matches dashboard.html RPC shapes.

   Rules:
   - Attaching a referral -> REFERRER gets +200 WP immediately, once.
   - Referred user reaches a 7-day streak -> REFERRER gets an additional +300 WP, once.
   - Maximum referral reward = +500 WP per referral.
   - 7-day qualification runs server-side inside claim_checkin (and via qualify_referral).
   - Clients have NO direct write access to any table (RPCs only).
   ============================================================ */

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

/* ---------------- TABLES ---------------- */

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  google_name text, avatar_url text, username text, x_username text,
  wp integer NOT NULL DEFAULT 0,
  streak integer NOT NULL DEFAULT 0,
  best_streak integer NOT NULL DEFAULT 0,
  last_checkin date,
  created_at timestamptz NOT NULL DEFAULT now(),
  wallet_address text,
  x_bonus_claimed boolean NOT NULL DEFAULT false,
  wallet_bonus_claimed boolean NOT NULL DEFAULT false,
  is_admin boolean NOT NULL DEFAULT false
);
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS google_name text,
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS username text,
  ADD COLUMN IF NOT EXISTS x_username text,
  ADD COLUMN IF NOT EXISTS wp integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS streak integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS best_streak integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_checkin date,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS wallet_address text,
  ADD COLUMN IF NOT EXISTS x_bonus_claimed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS wallet_bonus_claimed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.checkins (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  day date NOT NULL,
  day_in_cycle integer NOT NULL,
  wp_awarded integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.checkins
  ADD COLUMN IF NOT EXISTS day_in_cycle integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS wp_awarded integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.tasks (
  id text PRIMARY KEY,
  label text NOT NULL,
  url text NOT NULL,
  wp_reward integer NOT NULL,
  needs_proof boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS label text,
  ADD COLUMN IF NOT EXISTS url text,
  ADD COLUMN IF NOT EXISTS wp_reward integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS needs_proof boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.task_claims (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  task_id text NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  wp_awarded integer NOT NULL DEFAULT 0,
  proof_url text,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  status text DEFAULT 'pending',
  reviewed_at timestamptz,
  reviewed_by uuid
);
ALTER TABLE public.task_claims
  ADD COLUMN IF NOT EXISTS wp_awarded integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS proof_url text,
  ADD COLUMN IF NOT EXISTS claimed_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid;

CREATE TABLE IF NOT EXISTS public.referral_codes (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  referral_code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.referrals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  referred_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  referral_code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  initial_reward integer NOT NULL DEFAULT 200,
  initial_rewarded_at timestamptz,
  active_reward integer NOT NULL DEFAULT 300,
  active_rewarded_at timestamptz,
  qualified_at timestamptz
);
ALTER TABLE public.referrals
  ADD COLUMN IF NOT EXISTS initial_reward integer NOT NULL DEFAULT 200,
  ADD COLUMN IF NOT EXISTS initial_rewarded_at timestamptz,
  ADD COLUMN IF NOT EXISTS active_reward integer NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS active_rewarded_at timestamptz,
  ADD COLUMN IF NOT EXISTS qualified_at timestamptz;

CREATE TABLE IF NOT EXISTS public.referral_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referral_id bigint NOT NULL REFERENCES public.referrals(id) ON DELETE CASCADE,
  referrer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reward_type text NOT NULL,
  wp_awarded integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

/* ---------------- DEDUPE + INDEXES ---------------- */

/* New referrals use 200/300. Existing referral rows are not auto-credited by this repair script. */

DELETE FROM public.checkins a USING public.checkins b
 WHERE a.user_id = b.user_id AND a.day = b.day AND a.ctid < b.ctid;

DELETE FROM public.task_claims a USING public.task_claims b
 WHERE a.user_id = b.user_id AND a.task_id = b.task_id AND a.ctid < b.ctid;

CREATE UNIQUE INDEX IF NOT EXISTS checkins_user_day_unique ON public.checkins(user_id, day);
CREATE UNIQUE INDEX IF NOT EXISTS task_claims_user_task_unique ON public.task_claims(user_id, task_id);
CREATE UNIQUE INDEX IF NOT EXISTS referral_codes_code_unique ON public.referral_codes(referral_code);
CREATE UNIQUE INDEX IF NOT EXISTS referrals_referred_unique ON public.referrals(referred_id);
CREATE INDEX IF NOT EXISTS referrals_referrer_idx ON public.referrals(referrer_id);
CREATE INDEX IF NOT EXISTS referral_rewards_referrer_idx ON public.referral_rewards(referrer_id);
CREATE UNIQUE INDEX IF NOT EXISTS referral_rewards_referral_type_unique
  ON public.referral_rewards(referral_id, reward_type);
CREATE INDEX IF NOT EXISTS task_claims_status_idx ON public.task_claims(status);
CREATE INDEX IF NOT EXISTS profiles_wp_idx ON public.profiles(wp DESC);

/* ---------------- DROP OLD RPCs (return types may differ) ---------------- */

DO $$
DECLARE f text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'public.get_my_status()','public.claim_checkin()','public.record_portal_activity()',
    'public.get_task_board()','public.submit_task_for_review(text,text)',
    'public.get_admin_task_reviews()','public.approve_task_claim(uuid,text)',
    'public.reject_task_claim(uuid,text)','public.get_leaderboard(integer)',
    'public.get_admin_leaderboard()','public.get_admin_profile(uuid)',
    'public.update_profile(text,text)','public.update_profile(text,text,text)',
    'public.generate_referral_code()','public.get_my_referral_code()',
    'public.get_my_referral_data()','public.attach_referral(text)',
    'public.qualify_referral(uuid)','public.qualify_my_referral()',
    'public.get_my_referral_list()','public.get_my_referral_activity()',
    'public._qualify_referral_internal(uuid)'
  ] LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %s', f);
  END LOOP;
END $$;

/* ---------------- HELPERS ---------------- */

CREATE OR REPLACE FUNCTION public.manila_today()
RETURNS date LANGUAGE sql STABLE AS $$
  SELECT (now() AT TIME ZONE 'Asia/Manila')::date;
$$;

CREATE OR REPLACE FUNCTION public.manila_seconds_to_reset()
RETURNS integer LANGUAGE sql STABLE AS $$
  SELECT GREATEST(0, EXTRACT(EPOCH FROM (
    ((public.manila_today() + 1)::timestamp AT TIME ZONE 'Asia/Manila') - now()
  ))::integer);
$$;

DROP FUNCTION IF EXISTS public.effective_streak(date,integer);
CREATE FUNCTION public.effective_streak(p_last date, p_streak integer)
RETURNS integer LANGUAGE sql STABLE AS $$
  SELECT CASE
    WHEN p_last IS NULL THEN 0
    WHEN p_last >= public.manila_today() - 1 THEN COALESCE(p_streak,0)
    ELSE 0 END;
$$;

CREATE OR REPLACE FUNCTION public.wp_for_day(p_day integer)
RETURNS integer LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_day WHEN 1 THEN 5 WHEN 2 THEN 10 WHEN 3 THEN 15 WHEN 4 THEN 20
                    WHEN 5 THEN 25 WHEN 6 THEN 30 WHEN 7 THEN 50 ELSE 5 END;
$$;

CREATE OR REPLACE FUNCTION public.ensure_profile()
RETURNS public.profiles LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user uuid := auth.uid(); v_profile public.profiles;
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  INSERT INTO public.profiles (id, google_name, avatar_url)
  SELECT u.id,
         COALESCE(u.raw_user_meta_data->>'full_name', u.raw_user_meta_data->>'name'),
         COALESCE(u.raw_user_meta_data->>'avatar_url', u.raw_user_meta_data->>'picture')
  FROM auth.users u WHERE u.id = v_user
  ON CONFLICT (id) DO NOTHING;
  SELECT * INTO v_profile FROM public.profiles WHERE id = v_user;
  RETURN v_profile;
END $$;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT is_admin FROM public.profiles WHERE id = auth.uid()), false);
$$;

CREATE OR REPLACE FUNCTION public.is_valid_solana_address(p_wallet text)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
  SELECT btrim(COALESCE(p_wallet,'')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$';
$$;

/* ---------------- REFERRAL QUALIFICATION (internal, no auth check) ---------------- */

CREATE FUNCTION public._qualify_referral_internal(p_referred uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_ref public.referrals; v_streak integer;
  v_reward integer := 300; v_id bigint;
BEGIN
  SELECT * INTO v_ref
    FROM public.referrals
   WHERE referred_id = p_referred
   FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('rewarded', false, 'error', 'REFERRAL_NOT_FOUND');
  END IF;

  /* The +300 milestone can only be awarded once. */
  IF v_ref.active_rewarded_at IS NOT NULL
     OR EXISTS (
          SELECT 1 FROM public.referral_rewards rr
           WHERE rr.referral_id = v_ref.id
             AND rr.reward_type = 'active_referral'
        ) THEN
    RETURN jsonb_build_object(
      'rewarded', false,
      'already_rewarded', true,
      'wp_awarded', 0,
      'streak', 0
    );
  END IF;

  SELECT public.effective_streak(p.last_checkin, p.streak)
    INTO v_streak
    FROM public.profiles p
   WHERE p.id = p_referred;

  /* +300 is earned only when the referred Warden reaches a 7-day streak. */
  IF COALESCE(v_streak, 0) < 7 THEN
    RETURN jsonb_build_object(
      'rewarded', false,
      'qualified', false,
      'streak', COALESCE(v_streak, 0),
      'days_remaining', GREATEST(0, 7 - COALESCE(v_streak, 0))
    );
  END IF;

  INSERT INTO public.referral_rewards
    (referral_id, referrer_id, reward_type, wp_awarded)
  VALUES
    (v_ref.id, v_ref.referrer_id, 'active_referral', v_reward)
  ON CONFLICT (referral_id, reward_type) DO NOTHING
  RETURNING id INTO v_id;

  IF v_id IS NULL THEN
    RETURN jsonb_build_object(
      'rewarded', false,
      'already_rewarded', true,
      'wp_awarded', 0,
      'streak', v_streak
    );
  END IF;

  UPDATE public.referrals
     SET qualified_at = now(),
         active_reward = v_reward,
         active_rewarded_at = now()
   WHERE id = v_ref.id;

  UPDATE public.profiles
     SET wp = COALESCE(wp, 0) + v_reward
   WHERE id = v_ref.referrer_id;

  RETURN jsonb_build_object(
    'rewarded', true,
    'qualified', true,
    'wp_awarded', v_reward,
    'streak', v_streak,
    'referrer_id', v_ref.referrer_id,
    'referred_user', p_referred
  );
END $$;

CREATE FUNCTION public.qualify_referral(p_referred_user uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('rewarded', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  IF p_referred_user <> auth.uid() AND NOT public.is_current_user_admin() THEN
    RETURN jsonb_build_object('rewarded', false, 'error', 'FORBIDDEN');
  END IF;
  RETURN public._qualify_referral_internal(p_referred_user);
END $$;

CREATE FUNCTION public.qualify_my_referral()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT public.qualify_referral(auth.uid());
$$;

/* ---------------- CHECK-IN ---------------- */

CREATE FUNCTION public.get_my_status()
RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user uuid := auth.uid(); v_profile public.profiles; v_claimed boolean; v_rank integer;
BEGIN
  IF v_user IS NULL THEN
    RETURN json_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  v_profile := public.ensure_profile();

  SELECT EXISTS (SELECT 1 FROM public.checkins c
                 WHERE c.user_id = v_user AND c.day = public.manila_today()) INTO v_claimed;
  SELECT 1 + COUNT(*) INTO v_rank FROM public.profiles p WHERE p.wp > v_profile.wp;

  RETURN json_build_object(
    'ok', true, 'id', v_profile.id,
    'google_name', v_profile.google_name, 'avatar_url', v_profile.avatar_url,
    'username', v_profile.username, 'x_username', v_profile.x_username,
    'wallet_address', v_profile.wallet_address, 'wp', v_profile.wp,
    'streak', public.effective_streak(v_profile.last_checkin, v_profile.streak),
    'best_streak', v_profile.best_streak, 'last_checkin', v_profile.last_checkin,
    'claimed_today', v_claimed, 'rank', v_rank,
    'seconds_to_reset', public.manila_seconds_to_reset(),
    'is_admin', COALESCE(v_profile.is_admin, false));
END $$;

CREATE FUNCTION public.claim_checkin()
RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user uuid := auth.uid(); v_profile public.profiles; v_today date;
  v_streak integer; v_day integer; v_reward integer; v_rows integer;
BEGIN
  IF v_user IS NULL THEN
    RETURN json_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  PERFORM public.ensure_profile();
  SELECT * INTO v_profile FROM public.profiles WHERE id = v_user FOR UPDATE;

  v_today := public.manila_today();
  v_streak := CASE WHEN v_profile.last_checkin = v_today - 1
                   THEN COALESCE(v_profile.streak,0) + 1 ELSE 1 END;
  v_day := ((v_streak - 1) % 7) + 1;
  v_reward := public.wp_for_day(v_day);

  INSERT INTO public.checkins (user_id, day, day_in_cycle, wp_awarded)
  VALUES (v_user, v_today, v_day, v_reward)
  ON CONFLICT (user_id, day) DO NOTHING;
  GET DIAGNOSTICS v_rows = ROW_COUNT;

  IF v_rows = 0 THEN
    RETURN json_build_object('ok', false, 'error', 'ALREADY_CLAIMED', 'claimed_today', true);
  END IF;

  UPDATE public.profiles
     SET wp = COALESCE(wp,0) + v_reward, streak = v_streak,
         best_streak = GREATEST(COALESCE(best_streak,0), v_streak),
         last_checkin = v_today
   WHERE id = v_user;

  /* If this Warden was referred, check whether the +300 7-day milestone is now due. */
  PERFORM public._qualify_referral_internal(v_user);

  RETURN json_build_object('ok', true, 'wp_awarded', v_reward, 'day', v_day, 'streak', v_streak);
END $$;

CREATE FUNCTION public.record_portal_activity()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  PERFORM public.ensure_profile();
  RETURN jsonb_build_object('ok', true);
END $$;

/* ---------------- TASKS ---------------- */

CREATE FUNCTION public.get_task_board()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user uuid := auth.uid(); v_tasks jsonb; v_claims jsonb;
BEGIN
  IF v_user IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  PERFORM public.ensure_profile();

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'id', t.id, 'label', t.label, 'url', t.url, 'wp_reward', t.wp_reward,
    'needs_proof', t.needs_proof, 'active', t.active, 'sort_order', t.sort_order
  ) ORDER BY t.sort_order, t.created_at), '[]'::jsonb)
  INTO v_tasks FROM public.tasks t WHERE t.active = true;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'user_id', tc.user_id, 'task_id', tc.task_id, 'proof_url', tc.proof_url,
    'wp_awarded', tc.wp_awarded, 'status', COALESCE(tc.status, 'approved'),
    'claimed_at', tc.claimed_at, 'reviewed_at', tc.reviewed_at, 'reviewed_by', tc.reviewed_by
  ) ORDER BY tc.claimed_at DESC), '[]'::jsonb)
  INTO v_claims FROM public.task_claims tc WHERE tc.user_id = v_user;

  RETURN jsonb_build_object('ok', true, 'tasks', v_tasks, 'task_claims', v_claims);
END $$;

CREATE FUNCTION public.submit_task_for_review(p_task_id text, p_proof_url text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user uuid := auth.uid(); v_task public.tasks; v_existing public.task_claims; v_url text;
BEGIN
  IF v_user IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  PERFORM public.ensure_profile();

  v_url := btrim(COALESCE(p_proof_url, ''));
  IF v_url = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'PROOF_REQUIRED');
  END IF;
  IF v_url !~* '^https?://(www\.)?(x\.com|twitter\.com)/.+' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'INVALID_X_PROOF_URL');
  END IF;

  SELECT * INTO v_task FROM public.tasks WHERE id = p_task_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'UNKNOWN_TASK');
  END IF;
  IF NOT v_task.active THEN
    RETURN jsonb_build_object('ok', false, 'error', 'TASK_INACTIVE');
  END IF;

  SELECT * INTO v_existing FROM public.task_claims
   WHERE user_id = v_user AND task_id = p_task_id FOR UPDATE;

  IF FOUND THEN
    IF COALESCE(v_existing.status, 'approved') = 'approved' THEN
      RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_APPROVED');
    END IF;
    IF v_existing.status = 'pending' THEN
      RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_PENDING');
    END IF;
    UPDATE public.task_claims
       SET proof_url = v_url, status = 'pending', claimed_at = now(),
           reviewed_at = NULL, reviewed_by = NULL, wp_awarded = 0
     WHERE user_id = v_user AND task_id = p_task_id;
  ELSE
    INSERT INTO public.task_claims (user_id, task_id, wp_awarded, proof_url, claimed_at, status)
    VALUES (v_user, p_task_id, 0, v_url, now(), 'pending');
  END IF;

  RETURN jsonb_build_object('ok', true, 'status', 'pending', 'task_id', p_task_id);
EXCEPTION WHEN unique_violation THEN
  RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_PENDING');
END $$;

/* ---------------- ADMIN ---------------- */

CREATE FUNCTION public.get_admin_task_reviews()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_claims jsonb;
BEGIN
  IF NOT public.is_current_user_admin() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ADMIN_REQUIRED');
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'user_id', tc.user_id, 'task_id', tc.task_id, 'proof_url', tc.proof_url,
    'wp_awarded', tc.wp_awarded, 'status', tc.status, 'claimed_at', tc.claimed_at,
    'reviewed_at', tc.reviewed_at, 'reviewed_by', tc.reviewed_by,
    'username', p.username, 'google_name', p.google_name,
    'x_username', p.x_username, 'avatar_url', p.avatar_url,
    'task_label', t.label, 'task_url', t.url,
    'task_reward', t.wp_reward, 'wp_reward', t.wp_reward
  ) ORDER BY tc.claimed_at ASC), '[]'::jsonb)
  INTO v_claims
  FROM public.task_claims tc
  JOIN public.profiles p ON p.id = tc.user_id
  JOIN public.tasks t ON t.id = tc.task_id
  WHERE tc.status = 'pending';

  RETURN jsonb_build_object('ok', true, 'claims', v_claims);
END $$;

CREATE FUNCTION public.approve_task_claim(p_user_id uuid, p_task_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_claim public.task_claims; v_task public.tasks;
BEGIN
  IF NOT public.is_current_user_admin() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ADMIN_REQUIRED');
  END IF;

  SELECT * INTO v_claim FROM public.task_claims
   WHERE user_id = p_user_id AND task_id = p_task_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'CLAIM_NOT_FOUND');
  END IF;
  IF COALESCE(v_claim.status, 'approved') = 'approved' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_APPROVED');
  END IF;

  SELECT * INTO v_task FROM public.tasks WHERE id = p_task_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'UNKNOWN_TASK');
  END IF;

  UPDATE public.task_claims
     SET status = 'approved', wp_awarded = v_task.wp_reward,
         reviewed_at = now(), reviewed_by = auth.uid()
   WHERE user_id = p_user_id AND task_id = p_task_id;

  UPDATE public.profiles SET wp = COALESCE(wp,0) + v_task.wp_reward WHERE id = p_user_id;

  RETURN jsonb_build_object('ok', true, 'wp_awarded', v_task.wp_reward,
                            'task_id', p_task_id, 'user_id', p_user_id);
END $$;

CREATE FUNCTION public.reject_task_claim(p_user_id uuid, p_task_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_claim public.task_claims;
BEGIN
  IF NOT public.is_current_user_admin() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ADMIN_REQUIRED');
  END IF;

  SELECT * INTO v_claim FROM public.task_claims
   WHERE user_id = p_user_id AND task_id = p_task_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'CLAIM_NOT_FOUND');
  END IF;
  IF COALESCE(v_claim.status, 'approved') = 'approved' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_APPROVED');
  END IF;

  UPDATE public.task_claims
     SET status = 'rejected', reviewed_at = now(), reviewed_by = auth.uid(), wp_awarded = 0
   WHERE user_id = p_user_id AND task_id = p_task_id;

  RETURN jsonb_build_object('ok', true, 'status', 'rejected');
END $$;

/* ---------------- LEADERBOARD ---------------- */

CREATE FUNCTION public.get_leaderboard(p_limit integer)
RETURNS TABLE(pos bigint, display text, avatar text, x_handle text,
              points integer, day_streak integer, me boolean)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT ROW_NUMBER() OVER (ORDER BY p.wp DESC, p.streak DESC, p.created_at ASC),
         COALESCE(p.username, p.google_name, 'Warden'),
         p.avatar_url, p.x_username, COALESCE(p.wp, 0),
         public.effective_streak(p.last_checkin, p.streak),
         (p.id = auth.uid())
  FROM public.profiles p
  WHERE p.wp > 0
  ORDER BY p.wp DESC, p.streak DESC, p.created_at ASC
  LIMIT GREATEST(COALESCE(p_limit, 50), 1);
$$;

CREATE FUNCTION public.get_admin_leaderboard()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_profiles jsonb;
BEGIN
  IF NOT public.is_current_user_admin() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ADMIN_REQUIRED');
  END IF;

  SELECT COALESCE(jsonb_agg(x.j ORDER BY x.wp DESC, x.st DESC, x.ca ASC), '[]'::jsonb)
  INTO v_profiles
  FROM (
    SELECT p.wp, p.streak AS st, p.created_at AS ca,
           jsonb_build_object(
             'user_id', p.id, 'username', p.username, 'google_name', p.google_name,
             'x_username', p.x_username, 'wp', COALESCE(p.wp, 0),
             'streak', public.effective_streak(p.last_checkin, p.streak),
             'avatar_url', p.avatar_url) AS j
    FROM public.profiles p
    WHERE p.wp > 0
    ORDER BY p.wp DESC, p.streak DESC, p.created_at ASC
    LIMIT 50
  ) x;

  RETURN jsonb_build_object('ok', true, 'profiles', v_profiles);
END $$;

CREATE FUNCTION public.get_admin_profile(p_user_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_profile public.profiles;
BEGIN
  IF NOT public.is_current_user_admin() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ADMIN_REQUIRED');
  END IF;
  SELECT * INTO v_profile FROM public.profiles WHERE id = p_user_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'PROFILE_NOT_FOUND');
  END IF;
  RETURN jsonb_build_object('ok', true, 'profile', jsonb_build_object(
    'user_id', v_profile.id, 'username', v_profile.username,
    'google_name', v_profile.google_name, 'x_username', v_profile.x_username,
    'wp', v_profile.wp,
    'streak', public.effective_streak(v_profile.last_checkin, v_profile.streak),
    'best_streak', v_profile.best_streak,
    'wallet_address', v_profile.wallet_address, 'avatar_url', v_profile.avatar_url));
END $$;

/* ---------------- PROFILE ---------------- */

CREATE FUNCTION public.update_profile(p_username text, p_x_username text, p_wallet_address text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user uuid := auth.uid(); v_profile public.profiles;
  v_username text; v_x text; v_wallet text;
  v_x_bonus integer := 0; v_wallet_bonus integer := 0;
BEGIN
  IF v_user IS NULL THEN
    RETURN json_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  v_profile := public.ensure_profile();

  v_username := NULLIF(btrim(COALESCE(p_username, '')), '');
  v_x := NULLIF(btrim(regexp_replace(COALESCE(p_x_username, ''), '^@+', '')), '');
  v_wallet := NULLIF(btrim(COALESCE(p_wallet_address, '')), '');

  IF v_username IS NOT NULL AND v_username !~ '^[A-Za-z0-9_]{3,20}$' THEN
    RETURN json_build_object('ok', false, 'error', 'INVALID_USERNAME');
  END IF;
  IF v_username IS NOT NULL AND EXISTS (
       SELECT 1 FROM public.profiles p
        WHERE lower(p.username) = lower(v_username) AND p.id <> v_user) THEN
    RETURN json_build_object('ok', false, 'error', 'USERNAME_TAKEN');
  END IF;
  IF v_x IS NOT NULL AND v_x !~ '^[A-Za-z0-9_]{1,15}$' THEN
    RETURN json_build_object('ok', false, 'error', 'INVALID_X');
  END IF;
  IF v_wallet IS NOT NULL AND NOT public.is_valid_solana_address(v_wallet) THEN
    RETURN json_build_object('ok', false, 'error', 'INVALID_WALLET');
  END IF;

  IF v_x IS NOT NULL AND NOT COALESCE(v_profile.x_bonus_claimed, false) THEN
    v_x_bonus := 5;
  END IF;
  IF v_wallet IS NOT NULL AND NOT COALESCE(v_profile.wallet_bonus_claimed, false) THEN
    v_wallet_bonus := 5;
  END IF;

  UPDATE public.profiles
     SET username = v_username, x_username = v_x, wallet_address = v_wallet,
         x_bonus_claimed = x_bonus_claimed OR (v_x IS NOT NULL),
         wallet_bonus_claimed = wallet_bonus_claimed OR (v_wallet IS NOT NULL),
         wp = COALESCE(wp, 0) + v_x_bonus + v_wallet_bonus
   WHERE id = v_user
  RETURNING * INTO v_profile;

  RETURN json_build_object('ok', true, 'username', v_profile.username,
    'x_username', v_profile.x_username, 'wallet_address', v_profile.wallet_address,
    'x_bonus', v_x_bonus, 'wallet_bonus', v_wallet_bonus,
    'total_bonus', v_x_bonus + v_wallet_bonus);
END $$;

/* ---------------- REFERRALS ---------------- */

CREATE FUNCTION public.generate_referral_code()
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user uuid := auth.uid(); v_code text; v_try integer := 0;
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  PERFORM public.ensure_profile();

  SELECT referral_code INTO v_code FROM public.referral_codes WHERE user_id = v_user;
  IF v_code IS NOT NULL THEN RETURN v_code; END IF;

  LOOP
    v_try := v_try + 1;
    v_code := 'GW' || upper(substr(replace(
      CASE WHEN v_try = 1 THEN v_user::text ELSE gen_random_uuid()::text END,
      '-', ''), 1, 8));
    BEGIN
      INSERT INTO public.referral_codes (user_id, referral_code) VALUES (v_user, v_code);
      RETURN v_code;
    EXCEPTION WHEN unique_violation THEN
      SELECT referral_code INTO v_code FROM public.referral_codes WHERE user_id = v_user;
      IF v_code IS NOT NULL THEN RETURN v_code; END IF;
      IF v_try > 10 THEN RAISE; END IF;
    END;
  END LOOP;
END $$;

CREATE FUNCTION public.get_my_referral_code()
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN NULL; END IF;
  RETURN public.generate_referral_code();
END $$;

CREATE FUNCTION public.get_my_referral_data()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user uuid := auth.uid(); v_code text; v_total integer; v_successful integer;
  v_reward_count integer; v_total_wp integer; v_referred boolean;
  v_streak integer; v_checkins integer; v_qualified boolean;
BEGIN
  IF v_user IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'NOT_AUTHENTICATED');
  END IF;
  PERFORM public.ensure_profile();
  v_code := public.generate_referral_code();

  SELECT COUNT(*), COUNT(*) FILTER (WHERE qualified_at IS NOT NULL)
    INTO v_total, v_successful FROM public.referrals WHERE referrer_id = v_user;
  SELECT COUNT(*), COALESCE(SUM(wp_awarded), 0)
    INTO v_reward_count, v_total_wp FROM public.referral_rewards WHERE referrer_id = v_user;
  SELECT EXISTS (SELECT 1 FROM public.referrals WHERE referred_id = v_user) INTO v_referred;

  SELECT LEAST(COALESCE(public.effective_streak(p.last_checkin, p.streak), 0), 7)
    INTO v_streak FROM public.profiles p WHERE p.id = v_user;
  SELECT COUNT(*) INTO v_checkins FROM public.checkins WHERE user_id = v_user;

  v_qualified := EXISTS (SELECT 1 FROM public.referrals
                          WHERE referred_id = v_user AND qualified_at IS NOT NULL);

  RETURN jsonb_build_object(
    'ok', true, 'referral_code', v_code,
    'referral_link', 'https://thegreenwarden.xyz/dashboard.html?ref=' || COALESCE(v_code, ''),
    'referral_count', v_total, 'total_referrals', v_total,
    'successful_referrals', v_successful, 'reward_count', v_reward_count,
    'total_wp_earned', v_total_wp, 'has_been_referred', v_referred,
    'activity_streak', COALESCE(v_streak, 0), 'my_activity_streak', COALESCE(v_streak, 0),
    'checkins', v_checkins, 'days_remaining', GREATEST(0, 7 - COALESCE(v_streak, 0)),
    'qualified', v_qualified, 'my_7_day_qualified', v_qualified);
END $$;

CREATE FUNCTION public.attach_referral(p_code text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user uuid := auth.uid();
  v_code text;
  v_referrer uuid;
  v_referral_id bigint;
  v_reward_id bigint;
  v_initial_reward integer := 200;
BEGIN
  IF v_user IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'NOT_AUTHENTICATED',
                              'message', 'Please sign in first.');
  END IF;
  PERFORM public.ensure_profile();

  v_code := upper(btrim(COALESCE(p_code, '')));
  IF v_code = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID_CODE',
                              'message', 'Referral code is required.');
  END IF;

  SELECT user_id INTO v_referrer FROM public.referral_codes
   WHERE upper(referral_code) = v_code LIMIT 1;
  IF v_referrer IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID_CODE',
                              'message', 'Referral code not found.');
  END IF;
  IF v_referrer = v_user THEN
    RETURN jsonb_build_object('success', false, 'error', 'SELF_REFERRAL',
                              'message', 'You cannot use your own referral code.');
  END IF;
  IF EXISTS (SELECT 1 FROM public.referrals WHERE referred_id = v_user) THEN
    RETURN jsonb_build_object('success', false, 'error', 'ALREADY_REFERRED',
                              'message', 'This account already has a referral attached.');
  END IF;
  IF EXISTS (SELECT 1 FROM public.referrals
              WHERE referrer_id = v_user AND referred_id = v_referrer) THEN
    RETURN jsonb_build_object('success', false, 'error', 'CIRCULAR_REFERRAL',
                              'message', 'This Warden was referred by you.');
  END IF;

  /* Create the referral first. Acceptance itself earns +200 WP. */
  INSERT INTO public.referrals
    (referrer_id, referred_id, referral_code, initial_reward, active_reward)
  VALUES
    (v_referrer, v_user, v_code, 200, 300)
  RETURNING id INTO v_referral_id;

  /* Record the one-time +200 acceptance reward. */
  INSERT INTO public.referral_rewards
    (referral_id, referrer_id, reward_type, wp_awarded)
  VALUES
    (v_referral_id, v_referrer, 'initial_referral', v_initial_reward)
  ON CONFLICT (referral_id, reward_type) DO NOTHING
  RETURNING id INTO v_reward_id;

  IF v_reward_id IS NOT NULL THEN
    UPDATE public.referrals
       SET initial_reward = v_initial_reward,
           initial_rewarded_at = now()
     WHERE id = v_referral_id;

    UPDATE public.profiles
       SET wp = COALESCE(wp, 0) + v_initial_reward
     WHERE id = v_referrer;
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Referral accepted successfully. +200 WP awarded to the referrer.',
    'referrer_id', v_referrer,
    'referral_id', v_referral_id,
    'wp_awarded', CASE WHEN v_reward_id IS NOT NULL THEN v_initial_reward ELSE 0 END
  );
EXCEPTION WHEN unique_violation THEN
  RETURN jsonb_build_object('success', false, 'error', 'ALREADY_REFERRED',
                            'message', 'This account already has a referral attached.');
END $$;

CREATE FUNCTION public.get_my_referral_list()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'id', r.id, 'referred_id', r.referred_id, 'referral_code', r.referral_code,
    'created_at', r.created_at, 'qualified_at', r.qualified_at,
    'initial_reward', r.initial_reward, 'initial_rewarded_at', r.initial_rewarded_at,
    'active_reward', r.active_reward, 'active_rewarded_at', r.active_rewarded_at
  ) ORDER BY r.created_at DESC), '[]'::jsonb)
  FROM public.referrals r WHERE r.referrer_id = auth.uid();
$$;

CREATE FUNCTION public.get_my_referral_activity()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT public.get_my_referral_data();
$$;

/* ---------------- ROW LEVEL SECURITY ---------------- */

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_rewards ENABLE ROW LEVEL SECURITY;

/* profiles_update_own USED TO EXIST: it let any user edit their own wp / is_admin. Removed. */
DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
DROP POLICY IF EXISTS profiles_select_own ON public.profiles;
CREATE POLICY profiles_select_own ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());

DROP POLICY IF EXISTS checkins_select_own ON public.checkins;
CREATE POLICY checkins_select_own ON public.checkins FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS tasks_select_authenticated ON public.tasks;
CREATE POLICY tasks_select_authenticated ON public.tasks FOR SELECT TO authenticated USING (active = true);

DROP POLICY IF EXISTS task_claims_select_own ON public.task_claims;
CREATE POLICY task_claims_select_own ON public.task_claims FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS referral_codes_select_own ON public.referral_codes;
CREATE POLICY referral_codes_select_own ON public.referral_codes FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS referrals_select_own ON public.referrals;
CREATE POLICY referrals_select_own ON public.referrals FOR SELECT TO authenticated
  USING (referrer_id = auth.uid() OR referred_id = auth.uid());

DROP POLICY IF EXISTS referral_rewards_select_own ON public.referral_rewards;
CREATE POLICY referral_rewards_select_own ON public.referral_rewards FOR SELECT TO authenticated
  USING (referrer_id = auth.uid());

/* Clients may only READ their own rows; all writes go through RPCs. */
REVOKE ALL ON public.profiles, public.checkins, public.tasks, public.task_claims,
              public.referral_codes, public.referrals, public.referral_rewards FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.profiles, public.checkins, public.tasks,
              public.task_claims, public.referral_codes, public.referrals,
              public.referral_rewards FROM authenticated;
GRANT SELECT ON public.profiles, public.checkins, public.tasks, public.task_claims,
              public.referral_codes, public.referrals, public.referral_rewards TO authenticated;

/* ---------------- DEFAULT TASKS ---------------- */

INSERT INTO public.tasks (id, label, url, wp_reward, needs_proof, active, sort_order)
VALUES
 ('like-launch-post',  'Like + Reply to the Green Warden post',
  'https://x.com/GreenWardenSol/status/2102614430681022855?s=20', 50, true, true, 10),
 ('share-launch-post', 'Quote/Share the Green Warden post',
  'https://x.com/GreenWardenSol/status/2102614430681022855?s=20', 50, true, true, 20)
ON CONFLICT (id) DO UPDATE
  SET label = EXCLUDED.label, url = EXCLUDED.url, wp_reward = EXCLUDED.wp_reward,
      needs_proof = EXCLUDED.needs_proof, active = EXCLUDED.active, sort_order = EXCLUDED.sort_order;

/* ---------------- FUNCTION GRANTS ---------------- */

DO $$
DECLARE f text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'public.ensure_profile()','public.manila_today()','public.manila_seconds_to_reset()',
    'public.effective_streak(date,integer)','public.wp_for_day(integer)',
    'public.is_current_user_admin()','public.is_valid_solana_address(text)',
    'public.get_my_status()','public.claim_checkin()','public.record_portal_activity()',
    'public.get_task_board()','public.submit_task_for_review(text,text)',
    'public.get_admin_task_reviews()','public.approve_task_claim(uuid,text)',
    'public.reject_task_claim(uuid,text)','public.get_leaderboard(integer)',
    'public.get_admin_leaderboard()','public.get_admin_profile(uuid)',
    'public.update_profile(text,text,text)','public.generate_referral_code()',
    'public.get_my_referral_code()','public.get_my_referral_data()',
    'public.attach_referral(text)','public.qualify_referral(uuid)',
    'public.qualify_my_referral()','public.get_my_referral_list()',
    'public.get_my_referral_activity()','public._qualify_referral_internal(uuid)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated', f);
    IF f <> 'public._qualify_referral_internal(uuid)' THEN
      EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated', f);
    END IF;
  END LOOP;
END $$;

COMMIT;

/* ============================================================
   MAKE YOURSELF ADMIN (run once, with your own email):

   UPDATE public.profiles SET is_admin = true
   WHERE id = (SELECT id FROM auth.users WHERE email = 'you@example.com');
   ============================================================ */

/* ---------------- VERIFICATION ---------------- */

SELECT 'profiles' AS table_name, COUNT(*) AS rows FROM public.profiles
UNION ALL SELECT 'checkins', COUNT(*) FROM public.checkins
UNION ALL SELECT 'tasks', COUNT(*) FROM public.tasks
UNION ALL SELECT 'task_claims', COUNT(*) FROM public.task_claims
UNION ALL SELECT 'referral_codes', COUNT(*) FROM public.referral_codes
UNION ALL SELECT 'referrals', COUNT(*) FROM public.referrals
UNION ALL SELECT 'referral_rewards', COUNT(*) FROM public.referral_rewards;
